resources:
  # Resource for triggering pipeline
  - name: repo-read
    type: git
    icon: github
    source:
      uri: ((repo))
      branch: ((branch))
      username: ((git.username))
      password: ((git.password))
      # Determines what files trigger the pipeline
      paths:
        - ((project_root))
        - Dockerfile
        - requirements.txt

  # Resource for writing to the version file in the "version" branch of the repository
  - name: repo-write-version
    type: git
    icon: github
    source:
      uri: ((repo))
      branch: version
      username: ((git.username))
      password: ((git.password))

  # Production image registry resource
  - name: prod-image-registry
    type: registry-image
    source:
      repository: ((harbor.repository))/((image))
      username: ((harbor.username))
      password: ((harbor.password))
  
  # Development image registry resource
  - name: dev-image-registry
    type: registry-image
    source:
      repository: ((harbor.repository))/((image))
      tag: dev
      username: ((harbor.username))
      password: ((harbor.password))

  # Resource for versioning file
  - name: version
    type: semver
    icon: numeric
    source:
      initial_version: 0.0.1
      driver: git
      uri: ((ssh_url))
      branch: version
      file: version
      private_key: ((git.private_key))
      git_user: Concourse Bot <>
      commit_message: "Bump to version %version%"


jobs:
  # Trigger on merge from PR to main
  # pull dev sha, then scan for vulnerabilities as a gate (high / critical)
  # use semver as prod tag for prod image (Don't use "latest"!)
  # use "dev" as a tag, NOT appended at the end of the image name "project-dev" vs. "project:1.0.0-dev"
  
  # Trigger the pipeline when there is a PR merge to the "main" branch
  - name: trigger-pipeline
    plan:
      - get: repo-read
        trigger: true
  # Save the digest of the development image to a variable
  - name: get-dev-digest
    plan:
      - get: dev-image-registry
        format: oci
      - load_var: dev-digest
        file: dev-image/digest
  # Save the bumped version to a variable
  - name: get-bumped-version
    plan:
      - get: version
        params:
          bump: patch
      - load_var: bumped_version
        file: version/version
  # Push the dev image with the bumped version as the prod image
  - name: push-bumped-image
    plan:
      - put: prod-image-registry
        params:
          image: dev-image/image.tar
          version: ((.:bumped_version))
  # Push the new version to the version file in the "version" branch
  - name: push-new-version-file
    plan:
      - put: version
        params:
          version: ((.:bumped_version))
