apiVersion: batch/v1
kind: CronJob
metadata:
  name: prtg-meraki-snow-sync
  namespace: default
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # Environment variables added for Vault
            - env:
                - name: JWT_PATH
                  value: /var/run/secrets/kubernetes.io/serviceaccount/token
                - name: VAULT_ADDR
                  value: http://vault.vault:8200
              image: registry.quokka.ninja/ccfs/prtg-meraki-snow-sync/prtg-meraki-snow-sync:latest
              name: prtg-meraki-snow-sync
          # Credentials secret added for authorizing private repository
          imagePullSecrets:
            - name: gitlab-cr
          restartPolicy: OnFailure
          # Service Account added for Vault
          serviceAccountName: vault
      backoffLimit: 3
