repo: https://github.com/CC-Digital-Innovation/PRTG-Meraki-SNow-Sync
ssh_url: git@github.com:CC-Digital-Innovation/PRTG-Meraki-SNow-Sync.git
branch: dev
project_root: src
image: prtg-meraki-snow-sync-dev
manifest_path: ./infra/dev/job_dev.yml
pipeline: prtg-meraki-snow-sync-dev