resources:
  # Resource for triggering pipeline
  - name: repo-read
    type: git
    icon: github
    source:
      uri: ((repo))
      branch: ((branch))
      username: ((git.username))
      password: ((git.password))
      # Determines what files trigger the pipeline
      paths:
        - ((project_root))
        - Dockerfile
        - requirements.txt

  # Production image registry resource
  - name: prod-image-registry
    type: registry-image
    source:
      repository: ((harbor.repository))/((image))
      username: ((harbor.username))
      password: ((harbor.password))
  
  # Development image registry resource
  - name: dev-image-registry
    type: registry-image
    source:
      repository: ((harbor.repository))/((image))
      tag: dev
      username: ((harbor.username))
      password: ((harbor.password))

  # Resource for versioning file
  - name: versioning-file
    type: semver
    icon: numeric
    source:
      initial_version: 0.0.1
      driver: git
      uri: ((ssh_url))
      branch: version
      file: version
      private_key: ((git.private_key))
      git_user: "Concourse Bot <concourse.bot@example.com>"
      commit_message: "bump to version %version%"


jobs:
  - name: push-dev-image-to-prod
    plan:
      # Trigger the pipeline when there is a PR merge to the "main" branch
      - get: repo-read
        trigger: true
      # Get the dev image
      - get: dev-image-registry
        params:
          format: oci
      # Scan the dev image for vulnerabilities
      - task: trivy-scan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: aquasec/trivy
              tag: latest
          inputs:
            - name: dev-image-registry
          run:
            path: sh
            args:
              - -c
              - trivy image --no-progress --exit-code 1 --severity HIGH,CRITICAL --input dev-image-registry/image.tar
      # Get and bump the current version
      - get: versioning-file
        params:
          bump: patch
      # Save the bumped version to a variable
      - load_var: bumped_version
        file: versioning-file/version
      # Push the dev image with the bumped version as the prod image
      - put: prod-image-registry
        no_get: true
        params:
          image: dev-image-registry/image.tar
          version: ((.:bumped_version))
      # Push the new version to the version file in the "version" branch
      - put: versioning-file
        no_get: true
        params:
          bump: patch
